name: haphic
channels:
  - intel
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.6.15.2=ha878542_0
  - intel-openmp=2022.1.0=intel_3768
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libgomp=12.1.0=h8d9b700_16
  - liblapack=3.9.0=16_linux64_openblas
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libsqlite=3.39.3=h753d276_0
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.12=h166bdaf_3
  - mkl=2022.1.0=intel_223
  - ncurses=6.3=h27087fc_1
  - openssl=3.0.5=h166bdaf_2
  - pip=22.2.2=pyhd8ed1ab_0
  - python=3.10.6=ha86cf86_0_cpython
  - python_abi=3.10=2_cp310
  - readline=8.1.2=h0f457ee_0
  - setuptools=65.3.0=pyhd8ed1ab_1
  - sparse_dot_mkl=0.8.2=pyhd8ed1ab_0
  - tbb=2021.6.0=intel_835
  - tk=8.6.12=h27826a3_0
  - tzdata=2022c=h191b570_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
    - cycler==0.11.0
    - fonttools==4.37.1
    - joblib==1.1.0
    - kiwisolver==1.4.4
    - matplotlib==3.5.3
    - networkx==2.8.6
    - numpy==1.23.3
    - packaging==21.3
    - pillow==9.2.0
    - portion==2.3.0
    - pyparsing==3.0.9
    - pysam==0.19.1
    - python-dateutil==2.8.2
    - scikit-learn==1.1.2
    - scipy==1.9.1
    - six==1.16.0
    - sklearn==0.0
    - sortedcontainers==2.4.0
    - threadpoolctl==3.1.0
prefix: /work/home/zengxiaofei/software/miniconda3/envs/haphic
