name: haphic
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.7.4=hbcca054_0
  - icu=75.1=he02047a_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - libblas=3.9.0=23_linux64_openblas
  - libcblas=3.9.0=23_linux64_openblas
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=14.1.0=h77fa898_0
  - libgfortran-ng=14.1.0=h69a702a_0
  - libgfortran5=14.1.0=hc5f4f2c_0
  - libgomp=14.1.0=h77fa898_0
  - libhwloc=2.11.1=default_hecaa2ac_1000
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=23_linux64_openblas
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx-ng=14.1.0=hc0a3c3a_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=he7c6b58_4
  - libzlib=1.3.1=h4ab18f5_1
  - llvm-openmp=18.1.8=hf5423f3_0
  - mkl=2024.2.0=ha957f24_665
  - ncurses=6.5=h59595ed_0
  - numpy=1.26.4=py311h64a7726_0
  - openssl=3.3.1=h4bc722e_2
  - pip=24.2=pyhd8ed1ab_0
  - python=3.11.9=hb806964_0_cpython
  - python_abi=3.11=4_cp311
  - readline=8.2=h8228510_1
  - scipy=1.14.0=py311h517d4fd_1
  - setuptools=72.1.0=pyhd8ed1ab_0
  - sparse_dot_mkl=0.9.4=pyhd8ed1ab_0
  - tbb=2021.12.0=h434a139_3
  - tk=8.6.13=noxft_h4845f30_101
  - tzdata=2024a=h0c530f3_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - contourpy==1.2.1
      - cycler==0.12.1
      - fonttools==4.53.1
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - matplotlib==3.9.1.post1
      - networkx==3.3
      - packaging==24.1
      - pillow==10.4.0
      - portion==2.4.2
      - pyparsing==3.1.2
      - pysam==0.20.0
      - python-dateutil==2.9.0.post0
      - scikit-learn==1.5.1
      - six==1.16.0
      - sortedcontainers==2.4.0
      - threadpoolctl==3.5.0
prefix: /public/home/agis_zengxf/miniconda3/envs/haphic_py311
